<?php

return [
    [
        'name' => 'captcha_charset',
        'title' => '字符集',
        'type' => 'string',
        'content' => [],
        'value' => '2345678abcdefhijkmnpqrstuvwxyzABCDEFGHJKLMNPQRTUVWXY',
        'rule' => 'required:length(10~100)',
        'msg' => '',
        'tip' => '验证码字符集合',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_fontsize',
        'title' => '字体大小',
        'type' => 'radio',
        'content' => [
            16 => '16像素',
            18 => '18像素',
            20 => '20像素',
            24 => '24像素',
            36 => '36像素',
        ],
        'value' => '24',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证码字体大小(px)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_is_mixed',
        'title' => '混淆曲线',
        'type' => 'bool',
        'content' => [],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否画混淆曲线',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_is_cn',
        'title' => '中文字符',
        'type' => 'bool',
        'content' => [],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否使用中文验证码',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_height',
        'title' => '图片高度',
        'type' => 'number',
        'content' => [],
        'value' => '80',
        'rule' => 'required:range(40~80)',
        'msg' => '',
        'tip' => '验证码图片高度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_width',
        'title' => '图片宽度',
        'type' => 'number',
        'content' => [],
        'value' => '240',
        'rule' => 'required:range(130~260)',
        'msg' => '',
        'tip' => '验证码图片宽度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_size',
        'title' => '位数',
        'type' => 'number',
        'content' => [],
        'value' => '4',
        'rule' => 'required:range(1~8)',
        'msg' => '',
        'tip' => '验证码位数',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_is_reset',
        'title' => '重置',
        'type' => 'bool',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证成功后是否重置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_area',
        'title' => '验证码作用域',
        'type' => 'radio',
        'content' => [
            'all' => '全局',
            'forntend' => '仅前台',
            'backend' => '仅后台',
        ],
        'value' => 'backend',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证码配置的作用域',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captcha_is_close',
        'title' => '状态',
        'type' => 'radio',
        'content' => [
            '关闭验证',
            '开启验证',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否关闭验证码',
        'ok' => '',
        'extend' => '',
    ],
];
